[build]
  command = "npm run build"
  functions = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/api/v1/health"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
